name: Deploy Site on push
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, mysql
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.1'

      - name: Installing NPM Dependencies
        run: npm install

      - name: Building the project (Vue.js with Inertia)
        run: npm run production

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist

      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create Storage Link
        run: php artisan storage:link

      - name: Optimize Laravel Application
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          # Optional: php artisan migrate --force

      - name: Set Directory Permissions
        run: chmod -R 755 storage bootstrap/cache

      - name: 📂 Sync files to Shared Hosting
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.LARAVEL_SITE_SERVER }}
          username: ${{ secrets.LARAVEL_SITE_USER }}
          password: ${{ secrets.LARAVEL_SITE_PASS }}
